apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-ish-cloud-tls
spec:
  secretName: k8s-ish-cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.ish.cloud
  dnsNames:
    - k8s.ish.cloud
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.ish.cloud
